
version: '3.8'
services:
  app:
    build: .
    ports:
      - "8008:8008"  
    volumes:
      - ./app:/app
      
      - ./data:/data
    environment:
      - QDRANT_HOST=qdrant
    depends_on:
      - qdrant

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data:
