version: '3.8'
services:
  app:
    build: .
    ports:
      - "8008:8008"
    volumes:
      - ./app:/app
      - ./data:/data
    environment:
      - QDRANT_HOST=qdrant
      - POSTGRES_PORT=5433  # Add this line to make the port change explicit
    depends_on:
      - qdrant

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "5433:5432"  # This maps host port 5433 to container port 5432
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - POSTGRES_PORT=5432  # Internal container still uses 5432

volumes:
  qdrant_data: