# This configuration creates a separate PostgreSQL instance on port 5434
version: '3.8'
services:
  app:
    build: .
    ports:
      - "8008:8008"
    volumes:
      - ./app:/app
      - ./data:/data
    environment:
      # We use 5434 inside the container network
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=ragdb
      - POSTGRES_USER=raguser
      - POSTGRES_PASSWORD=ragpass
      - QDRANT_HOST=qdrant
    depends_on:
      - postgres
      - qdrant

  postgres:
    image: postgres:13
    ports:
      # Map container's 5432 to host's 5434
      - "5434:5432"
    environment:
      - POSTGRES_DB=ragdb
      - POSTGRES_USER=raguser
      - POSTGRES_PASSWORD=ragpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # Add healthcheck to ensure database is ready
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U raguser -d ragdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  postgres_data:
  qdrant_data:
